FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY WebApp.java .

RUN javac WebApp.java


FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/WebApp.class .

EXPOSE 8080

CMD ["java", "WebApp"]
